export default {
  success: true,
  data: {
    memes: [
      {
        id: "1",
        name: "Drake Hotline Bling",
        url: "http://i.imflip.com/30blgx.jpg",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: "2",
        name: "Two Buttons",
        url: "http://i.imflip.com/1g8my4.jpg",
        width: 600,
        height: 908,
        box_count: 3,
      },
      {
        id: "3",
        name: "Surprised Pikachu",
        url: "http://i.imflip.com/2kbnle.jpg",
        width: 1893,
        height: 1893,
        box_count: 3,
      },
      {
        id: "4",
        name: "Roll Safe Think About It",
        url: "http://i.imflip.com/1h7in3.jpg",
        width: 702,
        height: 395,
        box_count: 2,
      },
      {
        id: "5",
        name: "Bike Fall",
        url: "http://i.imflip.com/1b42wl.jpg",
        width: 500,
        height: 600,
        box_count: 3,
      },
      {
        id: "6",
        name: "One Does Not Simply",
        url: "http://i.imflip.com/1bij.jpg",
        width: 568,
        height: 335,
        box_count: 2,
      },
    ],
  },
};
